// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ConfigProto.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ca.stefanm.e39.proto;

@kotlin.jvm.JvmName("-initializeconfigProto")
public inline fun configProto(block: ca.stefanm.e39.proto.ConfigProtoKt.Dsl.() -> kotlin.Unit): ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto =
  ca.stefanm.e39.proto.ConfigProtoKt.Dsl._create(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ca.stefanm.e39.proto.ConfigProto`
 */
public object ConfigProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto = _builder.build()

    /**
     * `string str = 1;`
     */
    public var str: kotlin.String
      @JvmName("getStr")
      get() = _builder.getStr()
      @JvmName("setStr")
      set(value) {
        _builder.setStr(value)
      }
    /**
     * `string str = 1;`
     */
    public fun clearStr() {
      _builder.clearStr()
    }

    /**
     * `bool isIbusLogOutputEnabled = 2;`
     */
    public var isIbusLogOutputEnabled: kotlin.Boolean
      @JvmName("getIsIbusLogOutputEnabled")
      get() = _builder.getIsIbusLogOutputEnabled()
      @JvmName("setIsIbusLogOutputEnabled")
      set(value) {
        _builder.setIsIbusLogOutputEnabled(value)
      }
    /**
     * `bool isIbusLogOutputEnabled = 2;`
     */
    public fun clearIsIbusLogOutputEnabled() {
      _builder.clearIsIbusLogOutputEnabled()
    }

    /**
     * `.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForIbusLog = 3;`
     */
    public var enabledMaxLogLevelForIbusLog: ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels
      @JvmName("getEnabledMaxLogLevelForIbusLog")
      get() = _builder.getEnabledMaxLogLevelForIbusLog()
      @JvmName("setEnabledMaxLogLevelForIbusLog")
      set(value) {
        _builder.setEnabledMaxLogLevelForIbusLog(value)
      }
    public var enabledMaxLogLevelForIbusLogValue: kotlin.Int
      @JvmName("getEnabledMaxLogLevelForIbusLogValue")
      get() = _builder.getEnabledMaxLogLevelForIbusLogValue()
      @JvmName("setEnabledMaxLogLevelForIbusLogValue")
      set(value) {
        _builder.setEnabledMaxLogLevelForIbusLogValue(value)
      }
    /**
     * `.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForIbusLog = 3;`
     */
    public fun clearEnabledMaxLogLevelForIbusLog() {
      _builder.clearEnabledMaxLogLevelForIbusLog()
    }

    /**
     * `.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForPrintfLog = 4;`
     */
    public var enabledMaxLogLevelForPrintfLog: ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels
      @JvmName("getEnabledMaxLogLevelForPrintfLog")
      get() = _builder.getEnabledMaxLogLevelForPrintfLog()
      @JvmName("setEnabledMaxLogLevelForPrintfLog")
      set(value) {
        _builder.setEnabledMaxLogLevelForPrintfLog(value)
      }
    public var enabledMaxLogLevelForPrintfLogValue: kotlin.Int
      @JvmName("getEnabledMaxLogLevelForPrintfLogValue")
      get() = _builder.getEnabledMaxLogLevelForPrintfLogValue()
      @JvmName("setEnabledMaxLogLevelForPrintfLogValue")
      set(value) {
        _builder.setEnabledMaxLogLevelForPrintfLogValue(value)
      }
    /**
     * `.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForPrintfLog = 4;`
     */
    public fun clearEnabledMaxLogLevelForPrintfLog() {
      _builder.clearEnabledMaxLogLevelForPrintfLog()
    }

    /**
     * ```
     *If enabled, always turn on the Pi4 power supply when we start up.
     * ```
     *
     * `bool alwaysTurnOnRpiOnStatup = 5;`
     */
    public var alwaysTurnOnRpiOnStatup: kotlin.Boolean
      @JvmName("getAlwaysTurnOnRpiOnStatup")
      get() = _builder.getAlwaysTurnOnRpiOnStatup()
      @JvmName("setAlwaysTurnOnRpiOnStatup")
      set(value) {
        _builder.setAlwaysTurnOnRpiOnStatup(value)
      }
    /**
     * ```
     *If enabled, always turn on the Pi4 power supply when we start up.
     * ```
     *
     * `bool alwaysTurnOnRpiOnStatup = 5;`
     */
    public fun clearAlwaysTurnOnRpiOnStatup() {
      _builder.clearAlwaysTurnOnRpiOnStatup()
    }

    /**
     * ```
     *If enabled, send a packet to turn on BMBT screen
     * ```
     *
     * `bool alwaysTurnOnScreenOnIbusActivity = 6;`
     */
    public var alwaysTurnOnScreenOnIbusActivity: kotlin.Boolean
      @JvmName("getAlwaysTurnOnScreenOnIbusActivity")
      get() = _builder.getAlwaysTurnOnScreenOnIbusActivity()
      @JvmName("setAlwaysTurnOnScreenOnIbusActivity")
      set(value) {
        _builder.setAlwaysTurnOnScreenOnIbusActivity(value)
      }
    /**
     * ```
     *If enabled, send a packet to turn on BMBT screen
     * ```
     *
     * `bool alwaysTurnOnScreenOnIbusActivity = 6;`
     */
    public fun clearAlwaysTurnOnScreenOnIbusActivity() {
      _builder.clearAlwaysTurnOnScreenOnIbusActivity()
    }

    /**
     * `.ca.stefanm.e39.proto.ConfigProto.ScanProgram scanProgramOnBoot = 7;`
     */
    public var scanProgramOnBoot: ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram
      @JvmName("getScanProgramOnBoot")
      get() = _builder.getScanProgramOnBoot()
      @JvmName("setScanProgramOnBoot")
      set(value) {
        _builder.setScanProgramOnBoot(value)
      }
    public var scanProgramOnBootValue: kotlin.Int
      @JvmName("getScanProgramOnBootValue")
      get() = _builder.getScanProgramOnBootValue()
      @JvmName("setScanProgramOnBootValue")
      set(value) {
        _builder.setScanProgramOnBootValue(value)
      }
    /**
     * `.ca.stefanm.e39.proto.ConfigProto.ScanProgram scanProgramOnBoot = 7;`
     */
    public fun clearScanProgramOnBoot() {
      _builder.clearScanProgramOnBoot()
    }

    /**
     * `.ca.stefanm.e39.proto.ConfigProto.VideoSource videoSourceOnBoot = 8;`
     */
    public var videoSourceOnBoot: ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource
      @JvmName("getVideoSourceOnBoot")
      get() = _builder.getVideoSourceOnBoot()
      @JvmName("setVideoSourceOnBoot")
      set(value) {
        _builder.setVideoSourceOnBoot(value)
      }
    public var videoSourceOnBootValue: kotlin.Int
      @JvmName("getVideoSourceOnBootValue")
      get() = _builder.getVideoSourceOnBootValue()
      @JvmName("setVideoSourceOnBootValue")
      set(value) {
        _builder.setVideoSourceOnBootValue(value)
      }
    /**
     * `.ca.stefanm.e39.proto.ConfigProto.VideoSource videoSourceOnBoot = 8;`
     */
    public fun clearVideoSourceOnBoot() {
      _builder.clearVideoSourceOnBoot()
    }

    /**
     * ```
     *    https://github.com/piersholt/wilhelm-docs/blob/master/bmbt/4f.md
     * ```
     *
     * `bool sendBMBTEncodingPacketOnBootup = 9;`
     */
    public var sendBMBTEncodingPacketOnBootup: kotlin.Boolean
      @JvmName("getSendBMBTEncodingPacketOnBootup")
      get() = _builder.getSendBMBTEncodingPacketOnBootup()
      @JvmName("setSendBMBTEncodingPacketOnBootup")
      set(value) {
        _builder.setSendBMBTEncodingPacketOnBootup(value)
      }
    /**
     * ```
     *    https://github.com/piersholt/wilhelm-docs/blob/master/bmbt/4f.md
     * ```
     *
     * `bool sendBMBTEncodingPacketOnBootup = 9;`
     */
    public fun clearSendBMBTEncodingPacketOnBootup() {
      _builder.clearSendBMBTEncodingPacketOnBootup()
    }

    /**
     * `.ca.stefanm.e39.proto.ConfigProto.VideoEncoding videoEncoding = 10;`
     */
    public var videoEncoding: ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding
      @JvmName("getVideoEncoding")
      get() = _builder.getVideoEncoding()
      @JvmName("setVideoEncoding")
      set(value) {
        _builder.setVideoEncoding(value)
      }
    public var videoEncodingValue: kotlin.Int
      @JvmName("getVideoEncodingValue")
      get() = _builder.getVideoEncodingValue()
      @JvmName("setVideoEncodingValue")
      set(value) {
        _builder.setVideoEncodingValue(value)
      }
    /**
     * `.ca.stefanm.e39.proto.ConfigProto.VideoEncoding videoEncoding = 10;`
     */
    public fun clearVideoEncoding() {
      _builder.clearVideoEncoding()
    }

    /**
     * `.ca.stefanm.e39.proto.ConfigProto.AspectRatio aspectRatio = 11;`
     */
    public var aspectRatio: ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio
      @JvmName("getAspectRatio")
      get() = _builder.getAspectRatio()
      @JvmName("setAspectRatio")
      set(value) {
        _builder.setAspectRatio(value)
      }
    public var aspectRatioValue: kotlin.Int
      @JvmName("getAspectRatioValue")
      get() = _builder.getAspectRatioValue()
      @JvmName("setAspectRatioValue")
      set(value) {
        _builder.setAspectRatioValue(value)
      }
    /**
     * `.ca.stefanm.e39.proto.ConfigProto.AspectRatio aspectRatio = 11;`
     */
    public fun clearAspectRatio() {
      _builder.clearAspectRatio()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.copy(block: ca.stefanm.e39.proto.ConfigProtoKt.Dsl.() -> kotlin.Unit): ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto =
  ca.stefanm.e39.proto.ConfigProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

