// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: PicoToPi.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ca.stefanm.e39.proto;

