// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: PicoToPi.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ca.stefanm.e39.proto;

@kotlin.jvm.JvmName("-initializepicoToPi")
public inline fun picoToPi(block: ca.stefanm.e39.proto.PicoToPiKt.Dsl.() -> kotlin.Unit): ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi =
  ca.stefanm.e39.proto.PicoToPiKt.Dsl._create(ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ca.stefanm.e39.proto.PicoToPi`
 */
public object PicoToPiKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi = _builder.build()

    /**
     * `.ca.stefanm.e39.proto.PicoToPi.MessageType messageType = 1;`
     */
    public var messageType: ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType
      @JvmName("getMessageType")
      get() = _builder.getMessageType()
      @JvmName("setMessageType")
      set(value) {
        _builder.setMessageType(value)
      }
    public var messageTypeValue: kotlin.Int
      @JvmName("getMessageTypeValue")
      get() = _builder.getMessageTypeValue()
      @JvmName("setMessageTypeValue")
      set(value) {
        _builder.setMessageTypeValue(value)
      }
    /**
     * `.ca.stefanm.e39.proto.PicoToPi.MessageType messageType = 1;`
     */
    public fun clearMessageType() {
      _builder.clearMessageType()
    }

    /**
     * `.ca.stefanm.e39.proto.ConfigProto configMessage = 2;`
     */
    public var configMessage: ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto
      @JvmName("getConfigMessage")
      get() = _builder.getConfigMessage()
      @JvmName("setConfigMessage")
      set(value) {
        _builder.setConfigMessage(value)
      }
    /**
     * `.ca.stefanm.e39.proto.ConfigProto configMessage = 2;`
     */
    public fun clearConfigMessage() {
      _builder.clearConfigMessage()
    }
    /**
     * `.ca.stefanm.e39.proto.ConfigProto configMessage = 2;`
     * @return Whether the configMessage field is set.
     */
    public fun hasConfigMessage(): kotlin.Boolean {
      return _builder.hasConfigMessage()
    }

    /**
     * `string loggerStatement = 3;`
     */
    public var loggerStatement: kotlin.String
      @JvmName("getLoggerStatement")
      get() = _builder.getLoggerStatement()
      @JvmName("setLoggerStatement")
      set(value) {
        _builder.setLoggerStatement(value)
      }
    /**
     * `string loggerStatement = 3;`
     */
    public fun clearLoggerStatement() {
      _builder.clearLoggerStatement()
    }
    /**
     * `string loggerStatement = 3;`
     * @return Whether the loggerStatement field is set.
     */
    public fun hasLoggerStatement(): kotlin.Boolean {
      return _builder.hasLoggerStatement()
    }
    public val bodyCase: ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.BodyCase
      @JvmName("getBodyCase")
      get() = _builder.getBodyCase()

    public fun clearBody() {
      _builder.clearBody()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.copy(block: ca.stefanm.e39.proto.PicoToPiKt.Dsl.() -> kotlin.Unit): ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi =
  ca.stefanm.e39.proto.PicoToPiKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPiOrBuilder.configMessageOrNull: ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto?
  get() = if (hasConfigMessage()) getConfigMessage() else null

