// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigProto.proto

package ca.stefanm.e39.proto;

public final class ConfigProtoOuterClass {
  private ConfigProtoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ca.stefanm.e39.proto.ConfigProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string rpiFwGitCommitHash = 1;</code>
     * @return The rpiFwGitCommitHash.
     */
    java.lang.String getRpiFwGitCommitHash();
    /**
     * <code>string rpiFwGitCommitHash = 1;</code>
     * @return The bytes for rpiFwGitCommitHash.
     */
    com.google.protobuf.ByteString
        getRpiFwGitCommitHashBytes();

    /**
     * <code>bool isIbusLogOutputEnabled = 2;</code>
     * @return The isIbusLogOutputEnabled.
     */
    boolean getIsIbusLogOutputEnabled();

    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForIbusLog = 3;</code>
     * @return The enum numeric value on the wire for enabledMaxLogLevelForIbusLog.
     */
    int getEnabledMaxLogLevelForIbusLogValue();
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForIbusLog = 3;</code>
     * @return The enabledMaxLogLevelForIbusLog.
     */
    ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels getEnabledMaxLogLevelForIbusLog();

    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForPrintfLog = 4;</code>
     * @return The enum numeric value on the wire for enabledMaxLogLevelForPrintfLog.
     */
    int getEnabledMaxLogLevelForPrintfLogValue();
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForPrintfLog = 4;</code>
     * @return The enabledMaxLogLevelForPrintfLog.
     */
    ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels getEnabledMaxLogLevelForPrintfLog();

    /**
     * <pre>
     *If enabled, always turn on the Pi4 power supply when we start up.
     * </pre>
     *
     * <code>bool alwaysTurnOnRpiOnStatup = 5;</code>
     * @return The alwaysTurnOnRpiOnStatup.
     */
    boolean getAlwaysTurnOnRpiOnStatup();

    /**
     * <pre>
     *If enabled, send a packet to turn on BMBT screen
     * </pre>
     *
     * <code>bool alwaysTurnOnScreenOnIbusActivity = 6;</code>
     * @return The alwaysTurnOnScreenOnIbusActivity.
     */
    boolean getAlwaysTurnOnScreenOnIbusActivity();

    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.ScanProgram scanProgramOnBoot = 7;</code>
     * @return The enum numeric value on the wire for scanProgramOnBoot.
     */
    int getScanProgramOnBootValue();
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.ScanProgram scanProgramOnBoot = 7;</code>
     * @return The scanProgramOnBoot.
     */
    ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram getScanProgramOnBoot();

    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.VideoSource videoSourceOnBoot = 8;</code>
     * @return The enum numeric value on the wire for videoSourceOnBoot.
     */
    int getVideoSourceOnBootValue();
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.VideoSource videoSourceOnBoot = 8;</code>
     * @return The videoSourceOnBoot.
     */
    ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource getVideoSourceOnBoot();

    /**
     * <pre>
     *    https://github.com/piersholt/wilhelm-docs/blob/master/bmbt/4f.md
     * </pre>
     *
     * <code>bool sendBMBTEncodingPacketOnBootup = 9;</code>
     * @return The sendBMBTEncodingPacketOnBootup.
     */
    boolean getSendBMBTEncodingPacketOnBootup();

    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.VideoEncoding videoEncoding = 10;</code>
     * @return The enum numeric value on the wire for videoEncoding.
     */
    int getVideoEncodingValue();
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.VideoEncoding videoEncoding = 10;</code>
     * @return The videoEncoding.
     */
    ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding getVideoEncoding();

    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.AspectRatio aspectRatio = 11;</code>
     * @return The enum numeric value on the wire for aspectRatio.
     */
    int getAspectRatioValue();
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.AspectRatio aspectRatio = 11;</code>
     * @return The aspectRatio.
     */
    ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio getAspectRatio();
  }
  /**
   * Protobuf type {@code ca.stefanm.e39.proto.ConfigProto}
   */
  public static final class ConfigProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ca.stefanm.e39.proto.ConfigProto)
      ConfigProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigProto.newBuilder() to construct.
    private ConfigProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigProto() {
      rpiFwGitCommitHash_ = "";
      enabledMaxLogLevelForIbusLog_ = 0;
      enabledMaxLogLevelForPrintfLog_ = 0;
      scanProgramOnBoot_ = 0;
      videoSourceOnBoot_ = 0;
      videoEncoding_ = 0;
      aspectRatio_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigProto();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.stefanm.e39.proto.ConfigProtoOuterClass.internal_static_ca_stefanm_e39_proto_ConfigProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.stefanm.e39.proto.ConfigProtoOuterClass.internal_static_ca_stefanm_e39_proto_ConfigProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.class, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder.class);
    }

    /**
     * Protobuf enum {@code ca.stefanm.e39.proto.ConfigProto.LoggingLevels}
     */
    public enum LoggingLevels
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEBUG = 0;</code>
       */
      DEBUG(0),
      /**
       * <code>INFO = 1;</code>
       */
      INFO(1),
      /**
       * <code>WARN = 2;</code>
       */
      WARN(2),
      /**
       * <code>ERROR = 3;</code>
       */
      ERROR(3),
      /**
       * <code>WTF = 4;</code>
       */
      WTF(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DEBUG = 0;</code>
       */
      public static final int DEBUG_VALUE = 0;
      /**
       * <code>INFO = 1;</code>
       */
      public static final int INFO_VALUE = 1;
      /**
       * <code>WARN = 2;</code>
       */
      public static final int WARN_VALUE = 2;
      /**
       * <code>ERROR = 3;</code>
       */
      public static final int ERROR_VALUE = 3;
      /**
       * <code>WTF = 4;</code>
       */
      public static final int WTF_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static LoggingLevels valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static LoggingLevels forNumber(int value) {
        switch (value) {
          case 0: return DEBUG;
          case 1: return INFO;
          case 2: return WARN;
          case 3: return ERROR;
          case 4: return WTF;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<LoggingLevels>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          LoggingLevels> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LoggingLevels>() {
              public LoggingLevels findValueByNumber(int number) {
                return LoggingLevels.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDescriptor().getEnumTypes().get(0);
      }

      private static final LoggingLevels[] VALUES = values();

      public static LoggingLevels valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private LoggingLevels(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ca.stefanm.e39.proto.ConfigProto.LoggingLevels)
    }

    /**
     * Protobuf enum {@code ca.stefanm.e39.proto.ConfigProto.ScanProgram}
     */
    public enum ScanProgram
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <code>CLOCK = 1;</code>
       */
      CLOCK(1),
      /**
       * <code>LINSTEROS_BOOTSPLASH = 2;</code>
       */
      LINSTEROS_BOOTSPLASH(2),
      /**
       * <code>GOOSE_BOOTSPLASH = 3;</code>
       */
      GOOSE_BOOTSPLASH(3),
      /**
       * <code>BMW_BOOTSPLASH = 4;</code>
       */
      BMW_BOOTSPLASH(4),
      /**
       * <code>MENU = 5;</code>
       */
      MENU(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <code>CLOCK = 1;</code>
       */
      public static final int CLOCK_VALUE = 1;
      /**
       * <code>LINSTEROS_BOOTSPLASH = 2;</code>
       */
      public static final int LINSTEROS_BOOTSPLASH_VALUE = 2;
      /**
       * <code>GOOSE_BOOTSPLASH = 3;</code>
       */
      public static final int GOOSE_BOOTSPLASH_VALUE = 3;
      /**
       * <code>BMW_BOOTSPLASH = 4;</code>
       */
      public static final int BMW_BOOTSPLASH_VALUE = 4;
      /**
       * <code>MENU = 5;</code>
       */
      public static final int MENU_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ScanProgram valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ScanProgram forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return CLOCK;
          case 2: return LINSTEROS_BOOTSPLASH;
          case 3: return GOOSE_BOOTSPLASH;
          case 4: return BMW_BOOTSPLASH;
          case 5: return MENU;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ScanProgram>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ScanProgram> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ScanProgram>() {
              public ScanProgram findValueByNumber(int number) {
                return ScanProgram.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDescriptor().getEnumTypes().get(1);
      }

      private static final ScanProgram[] VALUES = values();

      public static ScanProgram valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ScanProgram(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ca.stefanm.e39.proto.ConfigProto.ScanProgram)
    }

    /**
     * Protobuf enum {@code ca.stefanm.e39.proto.ConfigProto.VideoSource}
     */
    public enum VideoSource
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RVC = 0;</code>
       */
      RVC(0),
      /**
       * <code>UPSTREAM = 1;</code>
       */
      UPSTREAM(1),
      /**
       * <code>PICO = 2;</code>
       */
      PICO(2),
      /**
       * <code>PI = 3;</code>
       */
      PI(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>RVC = 0;</code>
       */
      public static final int RVC_VALUE = 0;
      /**
       * <code>UPSTREAM = 1;</code>
       */
      public static final int UPSTREAM_VALUE = 1;
      /**
       * <code>PICO = 2;</code>
       */
      public static final int PICO_VALUE = 2;
      /**
       * <code>PI = 3;</code>
       */
      public static final int PI_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static VideoSource valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static VideoSource forNumber(int value) {
        switch (value) {
          case 0: return RVC;
          case 1: return UPSTREAM;
          case 2: return PICO;
          case 3: return PI;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<VideoSource>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          VideoSource> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<VideoSource>() {
              public VideoSource findValueByNumber(int number) {
                return VideoSource.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDescriptor().getEnumTypes().get(2);
      }

      private static final VideoSource[] VALUES = values();

      public static VideoSource valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private VideoSource(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ca.stefanm.e39.proto.ConfigProto.VideoSource)
    }

    /**
     * Protobuf enum {@code ca.stefanm.e39.proto.ConfigProto.VideoEncoding}
     */
    public enum VideoEncoding
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NTSC = 0;</code>
       */
      NTSC(0),
      /**
       * <code>PAL = 1;</code>
       */
      PAL(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NTSC = 0;</code>
       */
      public static final int NTSC_VALUE = 0;
      /**
       * <code>PAL = 1;</code>
       */
      public static final int PAL_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static VideoEncoding valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static VideoEncoding forNumber(int value) {
        switch (value) {
          case 0: return NTSC;
          case 1: return PAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<VideoEncoding>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          VideoEncoding> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<VideoEncoding>() {
              public VideoEncoding findValueByNumber(int number) {
                return VideoEncoding.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDescriptor().getEnumTypes().get(3);
      }

      private static final VideoEncoding[] VALUES = values();

      public static VideoEncoding valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private VideoEncoding(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ca.stefanm.e39.proto.ConfigProto.VideoEncoding)
    }

    /**
     * Protobuf enum {@code ca.stefanm.e39.proto.ConfigProto.AspectRatio}
     */
    public enum AspectRatio
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FourThree = 0;</code>
       */
      FourThree(0),
      /**
       * <code>SixteenNine = 1;</code>
       */
      SixteenNine(1),
      /**
       * <code>Zoom = 2;</code>
       */
      Zoom(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FourThree = 0;</code>
       */
      public static final int FourThree_VALUE = 0;
      /**
       * <code>SixteenNine = 1;</code>
       */
      public static final int SixteenNine_VALUE = 1;
      /**
       * <code>Zoom = 2;</code>
       */
      public static final int Zoom_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static AspectRatio valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static AspectRatio forNumber(int value) {
        switch (value) {
          case 0: return FourThree;
          case 1: return SixteenNine;
          case 2: return Zoom;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AspectRatio>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          AspectRatio> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AspectRatio>() {
              public AspectRatio findValueByNumber(int number) {
                return AspectRatio.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDescriptor().getEnumTypes().get(4);
      }

      private static final AspectRatio[] VALUES = values();

      public static AspectRatio valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private AspectRatio(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ca.stefanm.e39.proto.ConfigProto.AspectRatio)
    }

    public static final int RPIFWGITCOMMITHASH_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rpiFwGitCommitHash_ = "";
    /**
     * <code>string rpiFwGitCommitHash = 1;</code>
     * @return The rpiFwGitCommitHash.
     */
    @java.lang.Override
    public java.lang.String getRpiFwGitCommitHash() {
      java.lang.Object ref = rpiFwGitCommitHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rpiFwGitCommitHash_ = s;
        return s;
      }
    }
    /**
     * <code>string rpiFwGitCommitHash = 1;</code>
     * @return The bytes for rpiFwGitCommitHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRpiFwGitCommitHashBytes() {
      java.lang.Object ref = rpiFwGitCommitHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rpiFwGitCommitHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISIBUSLOGOUTPUTENABLED_FIELD_NUMBER = 2;
    private boolean isIbusLogOutputEnabled_ = false;
    /**
     * <code>bool isIbusLogOutputEnabled = 2;</code>
     * @return The isIbusLogOutputEnabled.
     */
    @java.lang.Override
    public boolean getIsIbusLogOutputEnabled() {
      return isIbusLogOutputEnabled_;
    }

    public static final int ENABLEDMAXLOGLEVELFORIBUSLOG_FIELD_NUMBER = 3;
    private int enabledMaxLogLevelForIbusLog_ = 0;
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForIbusLog = 3;</code>
     * @return The enum numeric value on the wire for enabledMaxLogLevelForIbusLog.
     */
    @java.lang.Override public int getEnabledMaxLogLevelForIbusLogValue() {
      return enabledMaxLogLevelForIbusLog_;
    }
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForIbusLog = 3;</code>
     * @return The enabledMaxLogLevelForIbusLog.
     */
    @java.lang.Override public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels getEnabledMaxLogLevelForIbusLog() {
      ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.forNumber(enabledMaxLogLevelForIbusLog_);
      return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.UNRECOGNIZED : result;
    }

    public static final int ENABLEDMAXLOGLEVELFORPRINTFLOG_FIELD_NUMBER = 4;
    private int enabledMaxLogLevelForPrintfLog_ = 0;
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForPrintfLog = 4;</code>
     * @return The enum numeric value on the wire for enabledMaxLogLevelForPrintfLog.
     */
    @java.lang.Override public int getEnabledMaxLogLevelForPrintfLogValue() {
      return enabledMaxLogLevelForPrintfLog_;
    }
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForPrintfLog = 4;</code>
     * @return The enabledMaxLogLevelForPrintfLog.
     */
    @java.lang.Override public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels getEnabledMaxLogLevelForPrintfLog() {
      ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.forNumber(enabledMaxLogLevelForPrintfLog_);
      return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.UNRECOGNIZED : result;
    }

    public static final int ALWAYSTURNONRPIONSTATUP_FIELD_NUMBER = 5;
    private boolean alwaysTurnOnRpiOnStatup_ = false;
    /**
     * <pre>
     *If enabled, always turn on the Pi4 power supply when we start up.
     * </pre>
     *
     * <code>bool alwaysTurnOnRpiOnStatup = 5;</code>
     * @return The alwaysTurnOnRpiOnStatup.
     */
    @java.lang.Override
    public boolean getAlwaysTurnOnRpiOnStatup() {
      return alwaysTurnOnRpiOnStatup_;
    }

    public static final int ALWAYSTURNONSCREENONIBUSACTIVITY_FIELD_NUMBER = 6;
    private boolean alwaysTurnOnScreenOnIbusActivity_ = false;
    /**
     * <pre>
     *If enabled, send a packet to turn on BMBT screen
     * </pre>
     *
     * <code>bool alwaysTurnOnScreenOnIbusActivity = 6;</code>
     * @return The alwaysTurnOnScreenOnIbusActivity.
     */
    @java.lang.Override
    public boolean getAlwaysTurnOnScreenOnIbusActivity() {
      return alwaysTurnOnScreenOnIbusActivity_;
    }

    public static final int SCANPROGRAMONBOOT_FIELD_NUMBER = 7;
    private int scanProgramOnBoot_ = 0;
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.ScanProgram scanProgramOnBoot = 7;</code>
     * @return The enum numeric value on the wire for scanProgramOnBoot.
     */
    @java.lang.Override public int getScanProgramOnBootValue() {
      return scanProgramOnBoot_;
    }
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.ScanProgram scanProgramOnBoot = 7;</code>
     * @return The scanProgramOnBoot.
     */
    @java.lang.Override public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram getScanProgramOnBoot() {
      ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram.forNumber(scanProgramOnBoot_);
      return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram.UNRECOGNIZED : result;
    }

    public static final int VIDEOSOURCEONBOOT_FIELD_NUMBER = 8;
    private int videoSourceOnBoot_ = 0;
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.VideoSource videoSourceOnBoot = 8;</code>
     * @return The enum numeric value on the wire for videoSourceOnBoot.
     */
    @java.lang.Override public int getVideoSourceOnBootValue() {
      return videoSourceOnBoot_;
    }
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.VideoSource videoSourceOnBoot = 8;</code>
     * @return The videoSourceOnBoot.
     */
    @java.lang.Override public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource getVideoSourceOnBoot() {
      ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource.forNumber(videoSourceOnBoot_);
      return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource.UNRECOGNIZED : result;
    }

    public static final int SENDBMBTENCODINGPACKETONBOOTUP_FIELD_NUMBER = 9;
    private boolean sendBMBTEncodingPacketOnBootup_ = false;
    /**
     * <pre>
     *    https://github.com/piersholt/wilhelm-docs/blob/master/bmbt/4f.md
     * </pre>
     *
     * <code>bool sendBMBTEncodingPacketOnBootup = 9;</code>
     * @return The sendBMBTEncodingPacketOnBootup.
     */
    @java.lang.Override
    public boolean getSendBMBTEncodingPacketOnBootup() {
      return sendBMBTEncodingPacketOnBootup_;
    }

    public static final int VIDEOENCODING_FIELD_NUMBER = 10;
    private int videoEncoding_ = 0;
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.VideoEncoding videoEncoding = 10;</code>
     * @return The enum numeric value on the wire for videoEncoding.
     */
    @java.lang.Override public int getVideoEncodingValue() {
      return videoEncoding_;
    }
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.VideoEncoding videoEncoding = 10;</code>
     * @return The videoEncoding.
     */
    @java.lang.Override public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding getVideoEncoding() {
      ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding.forNumber(videoEncoding_);
      return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding.UNRECOGNIZED : result;
    }

    public static final int ASPECTRATIO_FIELD_NUMBER = 11;
    private int aspectRatio_ = 0;
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.AspectRatio aspectRatio = 11;</code>
     * @return The enum numeric value on the wire for aspectRatio.
     */
    @java.lang.Override public int getAspectRatioValue() {
      return aspectRatio_;
    }
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto.AspectRatio aspectRatio = 11;</code>
     * @return The aspectRatio.
     */
    @java.lang.Override public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio getAspectRatio() {
      ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio.forNumber(aspectRatio_);
      return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rpiFwGitCommitHash_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rpiFwGitCommitHash_);
      }
      if (isIbusLogOutputEnabled_ != false) {
        output.writeBool(2, isIbusLogOutputEnabled_);
      }
      if (enabledMaxLogLevelForIbusLog_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.DEBUG.getNumber()) {
        output.writeEnum(3, enabledMaxLogLevelForIbusLog_);
      }
      if (enabledMaxLogLevelForPrintfLog_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.DEBUG.getNumber()) {
        output.writeEnum(4, enabledMaxLogLevelForPrintfLog_);
      }
      if (alwaysTurnOnRpiOnStatup_ != false) {
        output.writeBool(5, alwaysTurnOnRpiOnStatup_);
      }
      if (alwaysTurnOnScreenOnIbusActivity_ != false) {
        output.writeBool(6, alwaysTurnOnScreenOnIbusActivity_);
      }
      if (scanProgramOnBoot_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram.NONE.getNumber()) {
        output.writeEnum(7, scanProgramOnBoot_);
      }
      if (videoSourceOnBoot_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource.RVC.getNumber()) {
        output.writeEnum(8, videoSourceOnBoot_);
      }
      if (sendBMBTEncodingPacketOnBootup_ != false) {
        output.writeBool(9, sendBMBTEncodingPacketOnBootup_);
      }
      if (videoEncoding_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding.NTSC.getNumber()) {
        output.writeEnum(10, videoEncoding_);
      }
      if (aspectRatio_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio.FourThree.getNumber()) {
        output.writeEnum(11, aspectRatio_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rpiFwGitCommitHash_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rpiFwGitCommitHash_);
      }
      if (isIbusLogOutputEnabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isIbusLogOutputEnabled_);
      }
      if (enabledMaxLogLevelForIbusLog_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.DEBUG.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, enabledMaxLogLevelForIbusLog_);
      }
      if (enabledMaxLogLevelForPrintfLog_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.DEBUG.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, enabledMaxLogLevelForPrintfLog_);
      }
      if (alwaysTurnOnRpiOnStatup_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, alwaysTurnOnRpiOnStatup_);
      }
      if (alwaysTurnOnScreenOnIbusActivity_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, alwaysTurnOnScreenOnIbusActivity_);
      }
      if (scanProgramOnBoot_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, scanProgramOnBoot_);
      }
      if (videoSourceOnBoot_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource.RVC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, videoSourceOnBoot_);
      }
      if (sendBMBTEncodingPacketOnBootup_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, sendBMBTEncodingPacketOnBootup_);
      }
      if (videoEncoding_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding.NTSC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, videoEncoding_);
      }
      if (aspectRatio_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio.FourThree.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, aspectRatio_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto)) {
        return super.equals(obj);
      }
      ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto other = (ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto) obj;

      if (!getRpiFwGitCommitHash()
          .equals(other.getRpiFwGitCommitHash())) return false;
      if (getIsIbusLogOutputEnabled()
          != other.getIsIbusLogOutputEnabled()) return false;
      if (enabledMaxLogLevelForIbusLog_ != other.enabledMaxLogLevelForIbusLog_) return false;
      if (enabledMaxLogLevelForPrintfLog_ != other.enabledMaxLogLevelForPrintfLog_) return false;
      if (getAlwaysTurnOnRpiOnStatup()
          != other.getAlwaysTurnOnRpiOnStatup()) return false;
      if (getAlwaysTurnOnScreenOnIbusActivity()
          != other.getAlwaysTurnOnScreenOnIbusActivity()) return false;
      if (scanProgramOnBoot_ != other.scanProgramOnBoot_) return false;
      if (videoSourceOnBoot_ != other.videoSourceOnBoot_) return false;
      if (getSendBMBTEncodingPacketOnBootup()
          != other.getSendBMBTEncodingPacketOnBootup()) return false;
      if (videoEncoding_ != other.videoEncoding_) return false;
      if (aspectRatio_ != other.aspectRatio_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RPIFWGITCOMMITHASH_FIELD_NUMBER;
      hash = (53 * hash) + getRpiFwGitCommitHash().hashCode();
      hash = (37 * hash) + ISIBUSLOGOUTPUTENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsIbusLogOutputEnabled());
      hash = (37 * hash) + ENABLEDMAXLOGLEVELFORIBUSLOG_FIELD_NUMBER;
      hash = (53 * hash) + enabledMaxLogLevelForIbusLog_;
      hash = (37 * hash) + ENABLEDMAXLOGLEVELFORPRINTFLOG_FIELD_NUMBER;
      hash = (53 * hash) + enabledMaxLogLevelForPrintfLog_;
      hash = (37 * hash) + ALWAYSTURNONRPIONSTATUP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAlwaysTurnOnRpiOnStatup());
      hash = (37 * hash) + ALWAYSTURNONSCREENONIBUSACTIVITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAlwaysTurnOnScreenOnIbusActivity());
      hash = (37 * hash) + SCANPROGRAMONBOOT_FIELD_NUMBER;
      hash = (53 * hash) + scanProgramOnBoot_;
      hash = (37 * hash) + VIDEOSOURCEONBOOT_FIELD_NUMBER;
      hash = (53 * hash) + videoSourceOnBoot_;
      hash = (37 * hash) + SENDBMBTENCODINGPACKETONBOOTUP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSendBMBTEncodingPacketOnBootup());
      hash = (37 * hash) + VIDEOENCODING_FIELD_NUMBER;
      hash = (53 * hash) + videoEncoding_;
      hash = (37 * hash) + ASPECTRATIO_FIELD_NUMBER;
      hash = (53 * hash) + aspectRatio_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ca.stefanm.e39.proto.ConfigProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ca.stefanm.e39.proto.ConfigProto)
        ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.stefanm.e39.proto.ConfigProtoOuterClass.internal_static_ca_stefanm_e39_proto_ConfigProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.stefanm.e39.proto.ConfigProtoOuterClass.internal_static_ca_stefanm_e39_proto_ConfigProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.class, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder.class);
      }

      // Construct using ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        rpiFwGitCommitHash_ = "";
        isIbusLogOutputEnabled_ = false;
        enabledMaxLogLevelForIbusLog_ = 0;
        enabledMaxLogLevelForPrintfLog_ = 0;
        alwaysTurnOnRpiOnStatup_ = false;
        alwaysTurnOnScreenOnIbusActivity_ = false;
        scanProgramOnBoot_ = 0;
        videoSourceOnBoot_ = 0;
        sendBMBTEncodingPacketOnBootup_ = false;
        videoEncoding_ = 0;
        aspectRatio_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.stefanm.e39.proto.ConfigProtoOuterClass.internal_static_ca_stefanm_e39_proto_ConfigProto_descriptor;
      }

      @java.lang.Override
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto getDefaultInstanceForType() {
        return ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance();
      }

      @java.lang.Override
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto build() {
        ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto buildPartial() {
        ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto result = new ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rpiFwGitCommitHash_ = rpiFwGitCommitHash_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.isIbusLogOutputEnabled_ = isIbusLogOutputEnabled_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.enabledMaxLogLevelForIbusLog_ = enabledMaxLogLevelForIbusLog_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.enabledMaxLogLevelForPrintfLog_ = enabledMaxLogLevelForPrintfLog_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.alwaysTurnOnRpiOnStatup_ = alwaysTurnOnRpiOnStatup_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.alwaysTurnOnScreenOnIbusActivity_ = alwaysTurnOnScreenOnIbusActivity_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.scanProgramOnBoot_ = scanProgramOnBoot_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.videoSourceOnBoot_ = videoSourceOnBoot_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.sendBMBTEncodingPacketOnBootup_ = sendBMBTEncodingPacketOnBootup_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.videoEncoding_ = videoEncoding_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.aspectRatio_ = aspectRatio_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto) {
          return mergeFrom((ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto other) {
        if (other == ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance()) return this;
        if (!other.getRpiFwGitCommitHash().isEmpty()) {
          rpiFwGitCommitHash_ = other.rpiFwGitCommitHash_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getIsIbusLogOutputEnabled() != false) {
          setIsIbusLogOutputEnabled(other.getIsIbusLogOutputEnabled());
        }
        if (other.enabledMaxLogLevelForIbusLog_ != 0) {
          setEnabledMaxLogLevelForIbusLogValue(other.getEnabledMaxLogLevelForIbusLogValue());
        }
        if (other.enabledMaxLogLevelForPrintfLog_ != 0) {
          setEnabledMaxLogLevelForPrintfLogValue(other.getEnabledMaxLogLevelForPrintfLogValue());
        }
        if (other.getAlwaysTurnOnRpiOnStatup() != false) {
          setAlwaysTurnOnRpiOnStatup(other.getAlwaysTurnOnRpiOnStatup());
        }
        if (other.getAlwaysTurnOnScreenOnIbusActivity() != false) {
          setAlwaysTurnOnScreenOnIbusActivity(other.getAlwaysTurnOnScreenOnIbusActivity());
        }
        if (other.scanProgramOnBoot_ != 0) {
          setScanProgramOnBootValue(other.getScanProgramOnBootValue());
        }
        if (other.videoSourceOnBoot_ != 0) {
          setVideoSourceOnBootValue(other.getVideoSourceOnBootValue());
        }
        if (other.getSendBMBTEncodingPacketOnBootup() != false) {
          setSendBMBTEncodingPacketOnBootup(other.getSendBMBTEncodingPacketOnBootup());
        }
        if (other.videoEncoding_ != 0) {
          setVideoEncodingValue(other.getVideoEncodingValue());
        }
        if (other.aspectRatio_ != 0) {
          setAspectRatioValue(other.getAspectRatioValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                rpiFwGitCommitHash_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                isIbusLogOutputEnabled_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                enabledMaxLogLevelForIbusLog_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                enabledMaxLogLevelForPrintfLog_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                alwaysTurnOnRpiOnStatup_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                alwaysTurnOnScreenOnIbusActivity_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                scanProgramOnBoot_ = input.readEnum();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                videoSourceOnBoot_ = input.readEnum();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                sendBMBTEncodingPacketOnBootup_ = input.readBool();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                videoEncoding_ = input.readEnum();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 88: {
                aspectRatio_ = input.readEnum();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object rpiFwGitCommitHash_ = "";
      /**
       * <code>string rpiFwGitCommitHash = 1;</code>
       * @return The rpiFwGitCommitHash.
       */
      public java.lang.String getRpiFwGitCommitHash() {
        java.lang.Object ref = rpiFwGitCommitHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rpiFwGitCommitHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rpiFwGitCommitHash = 1;</code>
       * @return The bytes for rpiFwGitCommitHash.
       */
      public com.google.protobuf.ByteString
          getRpiFwGitCommitHashBytes() {
        java.lang.Object ref = rpiFwGitCommitHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rpiFwGitCommitHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rpiFwGitCommitHash = 1;</code>
       * @param value The rpiFwGitCommitHash to set.
       * @return This builder for chaining.
       */
      public Builder setRpiFwGitCommitHash(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        rpiFwGitCommitHash_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string rpiFwGitCommitHash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRpiFwGitCommitHash() {
        rpiFwGitCommitHash_ = getDefaultInstance().getRpiFwGitCommitHash();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string rpiFwGitCommitHash = 1;</code>
       * @param value The bytes for rpiFwGitCommitHash to set.
       * @return This builder for chaining.
       */
      public Builder setRpiFwGitCommitHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rpiFwGitCommitHash_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean isIbusLogOutputEnabled_ ;
      /**
       * <code>bool isIbusLogOutputEnabled = 2;</code>
       * @return The isIbusLogOutputEnabled.
       */
      @java.lang.Override
      public boolean getIsIbusLogOutputEnabled() {
        return isIbusLogOutputEnabled_;
      }
      /**
       * <code>bool isIbusLogOutputEnabled = 2;</code>
       * @param value The isIbusLogOutputEnabled to set.
       * @return This builder for chaining.
       */
      public Builder setIsIbusLogOutputEnabled(boolean value) {

        isIbusLogOutputEnabled_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool isIbusLogOutputEnabled = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsIbusLogOutputEnabled() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isIbusLogOutputEnabled_ = false;
        onChanged();
        return this;
      }

      private int enabledMaxLogLevelForIbusLog_ = 0;
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForIbusLog = 3;</code>
       * @return The enum numeric value on the wire for enabledMaxLogLevelForIbusLog.
       */
      @java.lang.Override public int getEnabledMaxLogLevelForIbusLogValue() {
        return enabledMaxLogLevelForIbusLog_;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForIbusLog = 3;</code>
       * @param value The enum numeric value on the wire for enabledMaxLogLevelForIbusLog to set.
       * @return This builder for chaining.
       */
      public Builder setEnabledMaxLogLevelForIbusLogValue(int value) {
        enabledMaxLogLevelForIbusLog_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForIbusLog = 3;</code>
       * @return The enabledMaxLogLevelForIbusLog.
       */
      @java.lang.Override
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels getEnabledMaxLogLevelForIbusLog() {
        ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.forNumber(enabledMaxLogLevelForIbusLog_);
        return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.UNRECOGNIZED : result;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForIbusLog = 3;</code>
       * @param value The enabledMaxLogLevelForIbusLog to set.
       * @return This builder for chaining.
       */
      public Builder setEnabledMaxLogLevelForIbusLog(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        enabledMaxLogLevelForIbusLog_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForIbusLog = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnabledMaxLogLevelForIbusLog() {
        bitField0_ = (bitField0_ & ~0x00000004);
        enabledMaxLogLevelForIbusLog_ = 0;
        onChanged();
        return this;
      }

      private int enabledMaxLogLevelForPrintfLog_ = 0;
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForPrintfLog = 4;</code>
       * @return The enum numeric value on the wire for enabledMaxLogLevelForPrintfLog.
       */
      @java.lang.Override public int getEnabledMaxLogLevelForPrintfLogValue() {
        return enabledMaxLogLevelForPrintfLog_;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForPrintfLog = 4;</code>
       * @param value The enum numeric value on the wire for enabledMaxLogLevelForPrintfLog to set.
       * @return This builder for chaining.
       */
      public Builder setEnabledMaxLogLevelForPrintfLogValue(int value) {
        enabledMaxLogLevelForPrintfLog_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForPrintfLog = 4;</code>
       * @return The enabledMaxLogLevelForPrintfLog.
       */
      @java.lang.Override
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels getEnabledMaxLogLevelForPrintfLog() {
        ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.forNumber(enabledMaxLogLevelForPrintfLog_);
        return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels.UNRECOGNIZED : result;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForPrintfLog = 4;</code>
       * @param value The enabledMaxLogLevelForPrintfLog to set.
       * @return This builder for chaining.
       */
      public Builder setEnabledMaxLogLevelForPrintfLog(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.LoggingLevels value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        enabledMaxLogLevelForPrintfLog_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.LoggingLevels enabledMaxLogLevelForPrintfLog = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnabledMaxLogLevelForPrintfLog() {
        bitField0_ = (bitField0_ & ~0x00000008);
        enabledMaxLogLevelForPrintfLog_ = 0;
        onChanged();
        return this;
      }

      private boolean alwaysTurnOnRpiOnStatup_ ;
      /**
       * <pre>
       *If enabled, always turn on the Pi4 power supply when we start up.
       * </pre>
       *
       * <code>bool alwaysTurnOnRpiOnStatup = 5;</code>
       * @return The alwaysTurnOnRpiOnStatup.
       */
      @java.lang.Override
      public boolean getAlwaysTurnOnRpiOnStatup() {
        return alwaysTurnOnRpiOnStatup_;
      }
      /**
       * <pre>
       *If enabled, always turn on the Pi4 power supply when we start up.
       * </pre>
       *
       * <code>bool alwaysTurnOnRpiOnStatup = 5;</code>
       * @param value The alwaysTurnOnRpiOnStatup to set.
       * @return This builder for chaining.
       */
      public Builder setAlwaysTurnOnRpiOnStatup(boolean value) {

        alwaysTurnOnRpiOnStatup_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *If enabled, always turn on the Pi4 power supply when we start up.
       * </pre>
       *
       * <code>bool alwaysTurnOnRpiOnStatup = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlwaysTurnOnRpiOnStatup() {
        bitField0_ = (bitField0_ & ~0x00000010);
        alwaysTurnOnRpiOnStatup_ = false;
        onChanged();
        return this;
      }

      private boolean alwaysTurnOnScreenOnIbusActivity_ ;
      /**
       * <pre>
       *If enabled, send a packet to turn on BMBT screen
       * </pre>
       *
       * <code>bool alwaysTurnOnScreenOnIbusActivity = 6;</code>
       * @return The alwaysTurnOnScreenOnIbusActivity.
       */
      @java.lang.Override
      public boolean getAlwaysTurnOnScreenOnIbusActivity() {
        return alwaysTurnOnScreenOnIbusActivity_;
      }
      /**
       * <pre>
       *If enabled, send a packet to turn on BMBT screen
       * </pre>
       *
       * <code>bool alwaysTurnOnScreenOnIbusActivity = 6;</code>
       * @param value The alwaysTurnOnScreenOnIbusActivity to set.
       * @return This builder for chaining.
       */
      public Builder setAlwaysTurnOnScreenOnIbusActivity(boolean value) {

        alwaysTurnOnScreenOnIbusActivity_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *If enabled, send a packet to turn on BMBT screen
       * </pre>
       *
       * <code>bool alwaysTurnOnScreenOnIbusActivity = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlwaysTurnOnScreenOnIbusActivity() {
        bitField0_ = (bitField0_ & ~0x00000020);
        alwaysTurnOnScreenOnIbusActivity_ = false;
        onChanged();
        return this;
      }

      private int scanProgramOnBoot_ = 0;
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.ScanProgram scanProgramOnBoot = 7;</code>
       * @return The enum numeric value on the wire for scanProgramOnBoot.
       */
      @java.lang.Override public int getScanProgramOnBootValue() {
        return scanProgramOnBoot_;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.ScanProgram scanProgramOnBoot = 7;</code>
       * @param value The enum numeric value on the wire for scanProgramOnBoot to set.
       * @return This builder for chaining.
       */
      public Builder setScanProgramOnBootValue(int value) {
        scanProgramOnBoot_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.ScanProgram scanProgramOnBoot = 7;</code>
       * @return The scanProgramOnBoot.
       */
      @java.lang.Override
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram getScanProgramOnBoot() {
        ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram.forNumber(scanProgramOnBoot_);
        return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram.UNRECOGNIZED : result;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.ScanProgram scanProgramOnBoot = 7;</code>
       * @param value The scanProgramOnBoot to set.
       * @return This builder for chaining.
       */
      public Builder setScanProgramOnBoot(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.ScanProgram value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        scanProgramOnBoot_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.ScanProgram scanProgramOnBoot = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearScanProgramOnBoot() {
        bitField0_ = (bitField0_ & ~0x00000040);
        scanProgramOnBoot_ = 0;
        onChanged();
        return this;
      }

      private int videoSourceOnBoot_ = 0;
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.VideoSource videoSourceOnBoot = 8;</code>
       * @return The enum numeric value on the wire for videoSourceOnBoot.
       */
      @java.lang.Override public int getVideoSourceOnBootValue() {
        return videoSourceOnBoot_;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.VideoSource videoSourceOnBoot = 8;</code>
       * @param value The enum numeric value on the wire for videoSourceOnBoot to set.
       * @return This builder for chaining.
       */
      public Builder setVideoSourceOnBootValue(int value) {
        videoSourceOnBoot_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.VideoSource videoSourceOnBoot = 8;</code>
       * @return The videoSourceOnBoot.
       */
      @java.lang.Override
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource getVideoSourceOnBoot() {
        ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource.forNumber(videoSourceOnBoot_);
        return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource.UNRECOGNIZED : result;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.VideoSource videoSourceOnBoot = 8;</code>
       * @param value The videoSourceOnBoot to set.
       * @return This builder for chaining.
       */
      public Builder setVideoSourceOnBoot(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoSource value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        videoSourceOnBoot_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.VideoSource videoSourceOnBoot = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideoSourceOnBoot() {
        bitField0_ = (bitField0_ & ~0x00000080);
        videoSourceOnBoot_ = 0;
        onChanged();
        return this;
      }

      private boolean sendBMBTEncodingPacketOnBootup_ ;
      /**
       * <pre>
       *    https://github.com/piersholt/wilhelm-docs/blob/master/bmbt/4f.md
       * </pre>
       *
       * <code>bool sendBMBTEncodingPacketOnBootup = 9;</code>
       * @return The sendBMBTEncodingPacketOnBootup.
       */
      @java.lang.Override
      public boolean getSendBMBTEncodingPacketOnBootup() {
        return sendBMBTEncodingPacketOnBootup_;
      }
      /**
       * <pre>
       *    https://github.com/piersholt/wilhelm-docs/blob/master/bmbt/4f.md
       * </pre>
       *
       * <code>bool sendBMBTEncodingPacketOnBootup = 9;</code>
       * @param value The sendBMBTEncodingPacketOnBootup to set.
       * @return This builder for chaining.
       */
      public Builder setSendBMBTEncodingPacketOnBootup(boolean value) {

        sendBMBTEncodingPacketOnBootup_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *    https://github.com/piersholt/wilhelm-docs/blob/master/bmbt/4f.md
       * </pre>
       *
       * <code>bool sendBMBTEncodingPacketOnBootup = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendBMBTEncodingPacketOnBootup() {
        bitField0_ = (bitField0_ & ~0x00000100);
        sendBMBTEncodingPacketOnBootup_ = false;
        onChanged();
        return this;
      }

      private int videoEncoding_ = 0;
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.VideoEncoding videoEncoding = 10;</code>
       * @return The enum numeric value on the wire for videoEncoding.
       */
      @java.lang.Override public int getVideoEncodingValue() {
        return videoEncoding_;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.VideoEncoding videoEncoding = 10;</code>
       * @param value The enum numeric value on the wire for videoEncoding to set.
       * @return This builder for chaining.
       */
      public Builder setVideoEncodingValue(int value) {
        videoEncoding_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.VideoEncoding videoEncoding = 10;</code>
       * @return The videoEncoding.
       */
      @java.lang.Override
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding getVideoEncoding() {
        ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding.forNumber(videoEncoding_);
        return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding.UNRECOGNIZED : result;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.VideoEncoding videoEncoding = 10;</code>
       * @param value The videoEncoding to set.
       * @return This builder for chaining.
       */
      public Builder setVideoEncoding(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.VideoEncoding value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000200;
        videoEncoding_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.VideoEncoding videoEncoding = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideoEncoding() {
        bitField0_ = (bitField0_ & ~0x00000200);
        videoEncoding_ = 0;
        onChanged();
        return this;
      }

      private int aspectRatio_ = 0;
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.AspectRatio aspectRatio = 11;</code>
       * @return The enum numeric value on the wire for aspectRatio.
       */
      @java.lang.Override public int getAspectRatioValue() {
        return aspectRatio_;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.AspectRatio aspectRatio = 11;</code>
       * @param value The enum numeric value on the wire for aspectRatio to set.
       * @return This builder for chaining.
       */
      public Builder setAspectRatioValue(int value) {
        aspectRatio_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.AspectRatio aspectRatio = 11;</code>
       * @return The aspectRatio.
       */
      @java.lang.Override
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio getAspectRatio() {
        ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio result = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio.forNumber(aspectRatio_);
        return result == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio.UNRECOGNIZED : result;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.AspectRatio aspectRatio = 11;</code>
       * @param value The aspectRatio to set.
       * @return This builder for chaining.
       */
      public Builder setAspectRatio(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.AspectRatio value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000400;
        aspectRatio_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto.AspectRatio aspectRatio = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearAspectRatio() {
        bitField0_ = (bitField0_ & ~0x00000400);
        aspectRatio_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ca.stefanm.e39.proto.ConfigProto)
    }

    // @@protoc_insertion_point(class_scope:ca.stefanm.e39.proto.ConfigProto)
    private static final ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto();
    }

    public static ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigProto>
        PARSER = new com.google.protobuf.AbstractParser<ConfigProto>() {
      @java.lang.Override
      public ConfigProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ConfigProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_stefanm_e39_proto_ConfigProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_stefanm_e39_proto_ConfigProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ConfigProto.proto\022\024ca.stefanm.e39.prot" +
      "o\"\327\007\n\013ConfigProto\022\032\n\022rpiFwGitCommitHash\030" +
      "\001 \001(\t\022\036\n\026isIbusLogOutputEnabled\030\002 \001(\010\022U\n" +
      "\034enabledMaxLogLevelForIbusLog\030\003 \001(\0162/.ca" +
      ".stefanm.e39.proto.ConfigProto.LoggingLe" +
      "vels\022W\n\036enabledMaxLogLevelForPrintfLog\030\004" +
      " \001(\0162/.ca.stefanm.e39.proto.ConfigProto." +
      "LoggingLevels\022\037\n\027alwaysTurnOnRpiOnStatup" +
      "\030\005 \001(\010\022(\n alwaysTurnOnScreenOnIbusActivi" +
      "ty\030\006 \001(\010\022H\n\021scanProgramOnBoot\030\007 \001(\0162-.ca" +
      ".stefanm.e39.proto.ConfigProto.ScanProgr" +
      "am\022H\n\021videoSourceOnBoot\030\010 \001(\0162-.ca.stefa" +
      "nm.e39.proto.ConfigProto.VideoSource\022&\n\036" +
      "sendBMBTEncodingPacketOnBootup\030\t \001(\010\022F\n\r" +
      "videoEncoding\030\n \001(\0162/.ca.stefanm.e39.pro" +
      "to.ConfigProto.VideoEncoding\022B\n\013aspectRa" +
      "tio\030\013 \001(\0162-.ca.stefanm.e39.proto.ConfigP" +
      "roto.AspectRatio\"B\n\rLoggingLevels\022\t\n\005DEB" +
      "UG\020\000\022\010\n\004INFO\020\001\022\010\n\004WARN\020\002\022\t\n\005ERROR\020\003\022\007\n\003W" +
      "TF\020\004\"p\n\013ScanProgram\022\010\n\004NONE\020\000\022\t\n\005CLOCK\020\001" +
      "\022\030\n\024LINSTEROS_BOOTSPLASH\020\002\022\024\n\020GOOSE_BOOT" +
      "SPLASH\020\003\022\022\n\016BMW_BOOTSPLASH\020\004\022\010\n\004MENU\020\005\"6" +
      "\n\013VideoSource\022\007\n\003RVC\020\000\022\014\n\010UPSTREAM\020\001\022\010\n\004" +
      "PICO\020\002\022\006\n\002PI\020\003\"\"\n\rVideoEncoding\022\010\n\004NTSC\020" +
      "\000\022\007\n\003PAL\020\001\"7\n\013AspectRatio\022\r\n\tFourThree\020\000" +
      "\022\017\n\013SixteenNine\020\001\022\010\n\004Zoom\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ca_stefanm_e39_proto_ConfigProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ca_stefanm_e39_proto_ConfigProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_stefanm_e39_proto_ConfigProto_descriptor,
        new java.lang.String[] { "RpiFwGitCommitHash", "IsIbusLogOutputEnabled", "EnabledMaxLogLevelForIbusLog", "EnabledMaxLogLevelForPrintfLog", "AlwaysTurnOnRpiOnStatup", "AlwaysTurnOnScreenOnIbusActivity", "ScanProgramOnBoot", "VideoSourceOnBoot", "SendBMBTEncodingPacketOnBootup", "VideoEncoding", "AspectRatio", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
