// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PicoToPi.proto

package ca.stefanm.e39.proto;

public final class PicoToPiOuterClass {
  private PicoToPiOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PicoToPiOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ca.stefanm.e39.proto.PicoToPi)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ca.stefanm.e39.proto.PicoToPi.MessageType messageType = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    int getMessageTypeValue();
    /**
     * <code>.ca.stefanm.e39.proto.PicoToPi.MessageType messageType = 1;</code>
     * @return The messageType.
     */
    ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType getMessageType();

    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
     * @return Whether the configMessage field is set.
     */
    boolean hasConfigMessage();
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
     * @return The configMessage.
     */
    ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto getConfigMessage();
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
     */
    ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder getConfigMessageOrBuilder();

    /**
     * <code>string loggerStatement = 3;</code>
     * @return Whether the loggerStatement field is set.
     */
    boolean hasLoggerStatement();
    /**
     * <code>string loggerStatement = 3;</code>
     * @return The loggerStatement.
     */
    java.lang.String getLoggerStatement();
    /**
     * <code>string loggerStatement = 3;</code>
     * @return The bytes for loggerStatement.
     */
    com.google.protobuf.ByteString
        getLoggerStatementBytes();

    ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.BodyCase getBodyCase();
  }
  /**
   * Protobuf type {@code ca.stefanm.e39.proto.PicoToPi}
   */
  public static final class PicoToPi extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ca.stefanm.e39.proto.PicoToPi)
      PicoToPiOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PicoToPi.newBuilder() to construct.
    private PicoToPi(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PicoToPi() {
      messageType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PicoToPi();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.stefanm.e39.proto.PicoToPiOuterClass.internal_static_ca_stefanm_e39_proto_PicoToPi_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.stefanm.e39.proto.PicoToPiOuterClass.internal_static_ca_stefanm_e39_proto_PicoToPi_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.class, ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.Builder.class);
    }

    /**
     * Protobuf enum {@code ca.stefanm.e39.proto.PicoToPi.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>EmptyMessage = 0;</code>
       */
      EmptyMessage(0),
      /**
       * <code>HeartbeatRequest = 1;</code>
       */
      HeartbeatRequest(1),
      /**
       * <code>HeartbeatResponse = 2;</code>
       */
      HeartbeatResponse(2),
      /**
       * <pre>
       *For the logger on the pico to shuttle to Rpi.
       * </pre>
       *
       * <code>LogStatement = 3;</code>
       */
      LogStatement(3),
      /**
       * <pre>
       *Dump the config object
       * </pre>
       *
       * <code>ConfigStatusResponse = 4;</code>
       */
      ConfigStatusResponse(4),
      /**
       * <pre>
       *TODO we could have a mechanism where the pi sends to the pico
       *TODO the number of ibus events it processed (knob turn messages?)
       *TODO and if the pico isn't receiveng this heartbeat often enough,
       *TODO it could auto-restart the PI.
       * </pre>
       *
       * <code>PiSoftPowerRestartX = 5;</code>
       */
      PiSoftPowerRestartX(5),
      /**
       * <pre>
       *Ask the RPI to legit restart
       * </pre>
       *
       * <code>PiSoftPowerRestartPi = 6;</code>
       */
      PiSoftPowerRestartPi(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>EmptyMessage = 0;</code>
       */
      public static final int EmptyMessage_VALUE = 0;
      /**
       * <code>HeartbeatRequest = 1;</code>
       */
      public static final int HeartbeatRequest_VALUE = 1;
      /**
       * <code>HeartbeatResponse = 2;</code>
       */
      public static final int HeartbeatResponse_VALUE = 2;
      /**
       * <pre>
       *For the logger on the pico to shuttle to Rpi.
       * </pre>
       *
       * <code>LogStatement = 3;</code>
       */
      public static final int LogStatement_VALUE = 3;
      /**
       * <pre>
       *Dump the config object
       * </pre>
       *
       * <code>ConfigStatusResponse = 4;</code>
       */
      public static final int ConfigStatusResponse_VALUE = 4;
      /**
       * <pre>
       *TODO we could have a mechanism where the pi sends to the pico
       *TODO the number of ibus events it processed (knob turn messages?)
       *TODO and if the pico isn't receiveng this heartbeat often enough,
       *TODO it could auto-restart the PI.
       * </pre>
       *
       * <code>PiSoftPowerRestartX = 5;</code>
       */
      public static final int PiSoftPowerRestartX_VALUE = 5;
      /**
       * <pre>
       *Ask the RPI to legit restart
       * </pre>
       *
       * <code>PiSoftPowerRestartPi = 6;</code>
       */
      public static final int PiSoftPowerRestartPi_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return EmptyMessage;
          case 1: return HeartbeatRequest;
          case 2: return HeartbeatResponse;
          case 3: return LogStatement;
          case 4: return ConfigStatusResponse;
          case 5: return PiSoftPowerRestartX;
          case 6: return PiSoftPowerRestartPi;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ca.stefanm.e39.proto.PicoToPi.MessageType)
    }

    private int bodyCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      CONFIGMESSAGE(2),
      LOGGERSTATEMENT(3),
      BODY_NOT_SET(0);
      private final int value;
      private BodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static BodyCase forNumber(int value) {
        switch (value) {
          case 2: return CONFIGMESSAGE;
          case 3: return LOGGERSTATEMENT;
          case 0: return BODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_ = 0;
    /**
     * <code>.ca.stefanm.e39.proto.PicoToPi.MessageType messageType = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.ca.stefanm.e39.proto.PicoToPi.MessageType messageType = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override public ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType getMessageType() {
      ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType result = ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType.forNumber(messageType_);
      return result == null ? ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType.UNRECOGNIZED : result;
    }

    public static final int CONFIGMESSAGE_FIELD_NUMBER = 2;
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
     * @return Whether the configMessage field is set.
     */
    @java.lang.Override
    public boolean hasConfigMessage() {
      return bodyCase_ == 2;
    }
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
     * @return The configMessage.
     */
    @java.lang.Override
    public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto getConfigMessage() {
      if (bodyCase_ == 2) {
         return (ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto) body_;
      }
      return ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance();
    }
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
     */
    @java.lang.Override
    public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder getConfigMessageOrBuilder() {
      if (bodyCase_ == 2) {
         return (ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto) body_;
      }
      return ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance();
    }

    public static final int LOGGERSTATEMENT_FIELD_NUMBER = 3;
    /**
     * <code>string loggerStatement = 3;</code>
     * @return Whether the loggerStatement field is set.
     */
    public boolean hasLoggerStatement() {
      return bodyCase_ == 3;
    }
    /**
     * <code>string loggerStatement = 3;</code>
     * @return The loggerStatement.
     */
    public java.lang.String getLoggerStatement() {
      java.lang.Object ref = "";
      if (bodyCase_ == 3) {
        ref = body_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bodyCase_ == 3) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string loggerStatement = 3;</code>
     * @return The bytes for loggerStatement.
     */
    public com.google.protobuf.ByteString
        getLoggerStatementBytes() {
      java.lang.Object ref = "";
      if (bodyCase_ == 3) {
        ref = body_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (bodyCase_ == 3) {
          body_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageType_ != ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType.EmptyMessage.getNumber()) {
        output.writeEnum(1, messageType_);
      }
      if (bodyCase_ == 2) {
        output.writeMessage(2, (ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto) body_);
      }
      if (bodyCase_ == 3) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, body_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageType_ != ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType.EmptyMessage.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_);
      }
      if (bodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto) body_);
      }
      if (bodyCase_ == 3) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi)) {
        return super.equals(obj);
      }
      ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi other = (ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi) obj;

      if (messageType_ != other.messageType_) return false;
      if (!getBodyCase().equals(other.getBodyCase())) return false;
      switch (bodyCase_) {
        case 2:
          if (!getConfigMessage()
              .equals(other.getConfigMessage())) return false;
          break;
        case 3:
          if (!getLoggerStatement()
              .equals(other.getLoggerStatement())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      switch (bodyCase_) {
        case 2:
          hash = (37 * hash) + CONFIGMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getConfigMessage().hashCode();
          break;
        case 3:
          hash = (37 * hash) + LOGGERSTATEMENT_FIELD_NUMBER;
          hash = (53 * hash) + getLoggerStatement().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ca.stefanm.e39.proto.PicoToPi}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ca.stefanm.e39.proto.PicoToPi)
        ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPiOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.stefanm.e39.proto.PicoToPiOuterClass.internal_static_ca_stefanm_e39_proto_PicoToPi_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.stefanm.e39.proto.PicoToPiOuterClass.internal_static_ca_stefanm_e39_proto_PicoToPi_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.class, ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.Builder.class);
      }

      // Construct using ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        messageType_ = 0;
        if (configMessageBuilder_ != null) {
          configMessageBuilder_.clear();
        }
        bodyCase_ = 0;
        body_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.stefanm.e39.proto.PicoToPiOuterClass.internal_static_ca_stefanm_e39_proto_PicoToPi_descriptor;
      }

      @java.lang.Override
      public ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi getDefaultInstanceForType() {
        return ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.getDefaultInstance();
      }

      @java.lang.Override
      public ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi build() {
        ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi buildPartial() {
        ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi result = new ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.messageType_ = messageType_;
        }
      }

      private void buildPartialOneofs(ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi result) {
        result.bodyCase_ = bodyCase_;
        result.body_ = this.body_;
        if (bodyCase_ == 2 &&
            configMessageBuilder_ != null) {
          result.body_ = configMessageBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi) {
          return mergeFrom((ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi other) {
        if (other == ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.getDefaultInstance()) return this;
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        switch (other.getBodyCase()) {
          case CONFIGMESSAGE: {
            mergeConfigMessage(other.getConfigMessage());
            break;
          }
          case LOGGERSTATEMENT: {
            bodyCase_ = 3;
            body_ = other.body_;
            onChanged();
            break;
          }
          case BODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                messageType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getConfigMessageFieldBuilder().getBuilder(),
                    extensionRegistry);
                bodyCase_ = 2;
                break;
              } // case 18
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                bodyCase_ = 3;
                body_ = s;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bodyCase_ = 0;
      private java.lang.Object body_;
      public BodyCase
          getBodyCase() {
        return BodyCase.forNumber(
            bodyCase_);
      }

      public Builder clearBody() {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int messageType_ = 0;
      /**
       * <code>.ca.stefanm.e39.proto.PicoToPi.MessageType messageType = 1;</code>
       * @return The enum numeric value on the wire for messageType.
       */
      @java.lang.Override public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <code>.ca.stefanm.e39.proto.PicoToPi.MessageType messageType = 1;</code>
       * @param value The enum numeric value on the wire for messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.PicoToPi.MessageType messageType = 1;</code>
       * @return The messageType.
       */
      @java.lang.Override
      public ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType getMessageType() {
        ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType result = ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType.forNumber(messageType_);
        return result == null ? ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ca.stefanm.e39.proto.PicoToPi.MessageType messageType = 1;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.PicoToPi.MessageType messageType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder> configMessageBuilder_;
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
       * @return Whether the configMessage field is set.
       */
      @java.lang.Override
      public boolean hasConfigMessage() {
        return bodyCase_ == 2;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
       * @return The configMessage.
       */
      @java.lang.Override
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto getConfigMessage() {
        if (configMessageBuilder_ == null) {
          if (bodyCase_ == 2) {
            return (ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto) body_;
          }
          return ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance();
        } else {
          if (bodyCase_ == 2) {
            return configMessageBuilder_.getMessage();
          }
          return ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance();
        }
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
       */
      public Builder setConfigMessage(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto value) {
        if (configMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          configMessageBuilder_.setMessage(value);
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
       */
      public Builder setConfigMessage(
          ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder builderForValue) {
        if (configMessageBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          configMessageBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
       */
      public Builder mergeConfigMessage(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto value) {
        if (configMessageBuilder_ == null) {
          if (bodyCase_ == 2 &&
              body_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance()) {
            body_ = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.newBuilder((ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 2) {
            configMessageBuilder_.mergeFrom(value);
          } else {
            configMessageBuilder_.setMessage(value);
          }
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
       */
      public Builder clearConfigMessage() {
        if (configMessageBuilder_ == null) {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
          }
          configMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
       */
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder getConfigMessageBuilder() {
        return getConfigMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
       */
      @java.lang.Override
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder getConfigMessageOrBuilder() {
        if ((bodyCase_ == 2) && (configMessageBuilder_ != null)) {
          return configMessageBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 2) {
            return (ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto) body_;
          }
          return ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance();
        }
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto configMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder> 
          getConfigMessageFieldBuilder() {
        if (configMessageBuilder_ == null) {
          if (!(bodyCase_ == 2)) {
            body_ = ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance();
          }
          configMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder>(
                  (ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 2;
        onChanged();
        return configMessageBuilder_;
      }

      /**
       * <code>string loggerStatement = 3;</code>
       * @return Whether the loggerStatement field is set.
       */
      @java.lang.Override
      public boolean hasLoggerStatement() {
        return bodyCase_ == 3;
      }
      /**
       * <code>string loggerStatement = 3;</code>
       * @return The loggerStatement.
       */
      @java.lang.Override
      public java.lang.String getLoggerStatement() {
        java.lang.Object ref = "";
        if (bodyCase_ == 3) {
          ref = body_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bodyCase_ == 3) {
            body_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string loggerStatement = 3;</code>
       * @return The bytes for loggerStatement.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLoggerStatementBytes() {
        java.lang.Object ref = "";
        if (bodyCase_ == 3) {
          ref = body_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (bodyCase_ == 3) {
            body_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string loggerStatement = 3;</code>
       * @param value The loggerStatement to set.
       * @return This builder for chaining.
       */
      public Builder setLoggerStatement(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bodyCase_ = 3;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string loggerStatement = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoggerStatement() {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string loggerStatement = 3;</code>
       * @param value The bytes for loggerStatement to set.
       * @return This builder for chaining.
       */
      public Builder setLoggerStatementBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bodyCase_ = 3;
        body_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ca.stefanm.e39.proto.PicoToPi)
    }

    // @@protoc_insertion_point(class_scope:ca.stefanm.e39.proto.PicoToPi)
    private static final ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi();
    }

    public static ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PicoToPi>
        PARSER = new com.google.protobuf.AbstractParser<PicoToPi>() {
      @java.lang.Override
      public PicoToPi parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PicoToPi> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PicoToPi> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.stefanm.e39.proto.PicoToPiOuterClass.PicoToPi getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_stefanm_e39_proto_PicoToPi_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_stefanm_e39_proto_PicoToPi_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016PicoToPi.proto\022\024ca.stefanm.e39.proto\032\021" +
      "ConfigProto.proto\"\330\002\n\010PicoToPi\022?\n\013messag" +
      "eType\030\001 \001(\0162*.ca.stefanm.e39.proto.PicoT" +
      "oPi.MessageType\022:\n\rconfigMessage\030\002 \001(\0132!" +
      ".ca.stefanm.e39.proto.ConfigProtoH\000\022\031\n\017l" +
      "oggerStatement\030\003 \001(\tH\000\"\253\001\n\013MessageType\022\020" +
      "\n\014EmptyMessage\020\000\022\024\n\020HeartbeatRequest\020\001\022\025" +
      "\n\021HeartbeatResponse\020\002\022\020\n\014LogStatement\020\003\022" +
      "\030\n\024ConfigStatusResponse\020\004\022\027\n\023PiSoftPower" +
      "RestartX\020\005\022\030\n\024PiSoftPowerRestartPi\020\006B\006\n\004" +
      "bodyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.stefanm.e39.proto.ConfigProtoOuterClass.getDescriptor(),
        });
    internal_static_ca_stefanm_e39_proto_PicoToPi_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ca_stefanm_e39_proto_PicoToPi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_stefanm_e39_proto_PicoToPi_descriptor,
        new java.lang.String[] { "MessageType", "ConfigMessage", "LoggerStatement", "Body", });
    ca.stefanm.e39.proto.ConfigProtoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
