// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PiToPico.proto

package ca.stefanm.e39.proto;

public final class PiToPicoOuterClass {
  private PiToPicoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PiToPicoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ca.stefanm.e39.proto.PiToPico)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ca.stefanm.e39.proto.PiToPico.MessageType messageType = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    int getMessageTypeValue();
    /**
     * <code>.ca.stefanm.e39.proto.PiToPico.MessageType messageType = 1;</code>
     * @return The messageType.
     */
    ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType getMessageType();

    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
     * @return Whether the newConfig field is set.
     */
    boolean hasNewConfig();
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
     * @return The newConfig.
     */
    ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto getNewConfig();
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
     */
    ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder getNewConfigOrBuilder();
  }
  /**
   * Protobuf type {@code ca.stefanm.e39.proto.PiToPico}
   */
  public static final class PiToPico extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ca.stefanm.e39.proto.PiToPico)
      PiToPicoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PiToPico.newBuilder() to construct.
    private PiToPico(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PiToPico() {
      messageType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PiToPico();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.stefanm.e39.proto.PiToPicoOuterClass.internal_static_ca_stefanm_e39_proto_PiToPico_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.stefanm.e39.proto.PiToPicoOuterClass.internal_static_ca_stefanm_e39_proto_PiToPico_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.class, ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.Builder.class);
    }

    /**
     * <pre>
     *TODO Someday this could be a union proto type, but not this release.
     * </pre>
     *
     * Protobuf enum {@code ca.stefanm.e39.proto.PiToPico.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>EmptyMessage = 0;</code>
       */
      EmptyMessage(0),
      /**
       * <code>HeartbeatRequest = 1;</code>
       */
      HeartbeatRequest(1),
      /**
       * <code>HeartbeatResponse = 2;</code>
       */
      HeartbeatResponse(2),
      /**
       * <pre>
       *Instruct the pico to tell us what it's config object is
       * </pre>
       *
       * <code>ConfigStatusRequest = 3;</code>
       */
      ConfigStatusRequest(3),
      /**
       * <pre>
       *Tell the pico what it's new config object should be
       * </pre>
       *
       * <code>ConfigPush = 4;</code>
       */
      ConfigPush(4),
      /**
       * <pre>
       *Ask the pico to show upstream (for Back to BMW function)
       * </pre>
       *
       * <code>PicoVideoRequestUpstream = 5;</code>
       */
      PicoVideoRequestUpstream(5),
      /**
       * <pre>
       *Ask the pico to show the debug menu
       * </pre>
       *
       * <code>PicoVideoRequestPico = 6;</code>
       */
      PicoVideoRequestPico(6),
      /**
       * <pre>
       *Ask the pico to show the RPi.
       * </pre>
       *
       * <code>PicoVideoRequestRpi = 7;</code>
       */
      PicoVideoRequestRpi(7),
      /**
       * <code>PicoVideoRequestRVC = 8;</code>
       */
      PicoVideoRequestRVC(8),
      /**
       * <pre>
       *For test purposes to toggle the power switch for the RPI power supply.
       * </pre>
       *
       * <code>PicoPowerRequestOn = 9;</code>
       */
      PicoPowerRequestOn(9),
      /**
       * <code>PicoPowerRequestOff = 10;</code>
       */
      PicoPowerRequestOff(10),
      /**
       * <pre>
       *Allow us to simulate ignition events without a GM or LCM or ignition switch
       * </pre>
       *
       * <code>SimulatedIgnitionPosition0 = 11;</code>
       */
      SimulatedIgnitionPosition0(11),
      /**
       * <code>SimulatedIgnitionPosition1 = 12;</code>
       */
      SimulatedIgnitionPosition1(12),
      /**
       * <code>SimulatedIgnitionPosition2 = 13;</code>
       */
      SimulatedIgnitionPosition2(13),
      /**
       * <code>SimulatedIgnitionPosition3 = 14;</code>
       */
      SimulatedIgnitionPosition3(14),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>EmptyMessage = 0;</code>
       */
      public static final int EmptyMessage_VALUE = 0;
      /**
       * <code>HeartbeatRequest = 1;</code>
       */
      public static final int HeartbeatRequest_VALUE = 1;
      /**
       * <code>HeartbeatResponse = 2;</code>
       */
      public static final int HeartbeatResponse_VALUE = 2;
      /**
       * <pre>
       *Instruct the pico to tell us what it's config object is
       * </pre>
       *
       * <code>ConfigStatusRequest = 3;</code>
       */
      public static final int ConfigStatusRequest_VALUE = 3;
      /**
       * <pre>
       *Tell the pico what it's new config object should be
       * </pre>
       *
       * <code>ConfigPush = 4;</code>
       */
      public static final int ConfigPush_VALUE = 4;
      /**
       * <pre>
       *Ask the pico to show upstream (for Back to BMW function)
       * </pre>
       *
       * <code>PicoVideoRequestUpstream = 5;</code>
       */
      public static final int PicoVideoRequestUpstream_VALUE = 5;
      /**
       * <pre>
       *Ask the pico to show the debug menu
       * </pre>
       *
       * <code>PicoVideoRequestPico = 6;</code>
       */
      public static final int PicoVideoRequestPico_VALUE = 6;
      /**
       * <pre>
       *Ask the pico to show the RPi.
       * </pre>
       *
       * <code>PicoVideoRequestRpi = 7;</code>
       */
      public static final int PicoVideoRequestRpi_VALUE = 7;
      /**
       * <code>PicoVideoRequestRVC = 8;</code>
       */
      public static final int PicoVideoRequestRVC_VALUE = 8;
      /**
       * <pre>
       *For test purposes to toggle the power switch for the RPI power supply.
       * </pre>
       *
       * <code>PicoPowerRequestOn = 9;</code>
       */
      public static final int PicoPowerRequestOn_VALUE = 9;
      /**
       * <code>PicoPowerRequestOff = 10;</code>
       */
      public static final int PicoPowerRequestOff_VALUE = 10;
      /**
       * <pre>
       *Allow us to simulate ignition events without a GM or LCM or ignition switch
       * </pre>
       *
       * <code>SimulatedIgnitionPosition0 = 11;</code>
       */
      public static final int SimulatedIgnitionPosition0_VALUE = 11;
      /**
       * <code>SimulatedIgnitionPosition1 = 12;</code>
       */
      public static final int SimulatedIgnitionPosition1_VALUE = 12;
      /**
       * <code>SimulatedIgnitionPosition2 = 13;</code>
       */
      public static final int SimulatedIgnitionPosition2_VALUE = 13;
      /**
       * <code>SimulatedIgnitionPosition3 = 14;</code>
       */
      public static final int SimulatedIgnitionPosition3_VALUE = 14;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return EmptyMessage;
          case 1: return HeartbeatRequest;
          case 2: return HeartbeatResponse;
          case 3: return ConfigStatusRequest;
          case 4: return ConfigPush;
          case 5: return PicoVideoRequestUpstream;
          case 6: return PicoVideoRequestPico;
          case 7: return PicoVideoRequestRpi;
          case 8: return PicoVideoRequestRVC;
          case 9: return PicoPowerRequestOn;
          case 10: return PicoPowerRequestOff;
          case 11: return SimulatedIgnitionPosition0;
          case 12: return SimulatedIgnitionPosition1;
          case 13: return SimulatedIgnitionPosition2;
          case 14: return SimulatedIgnitionPosition3;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ca.stefanm.e39.proto.PiToPico.MessageType)
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_ = 0;
    /**
     * <code>.ca.stefanm.e39.proto.PiToPico.MessageType messageType = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.ca.stefanm.e39.proto.PiToPico.MessageType messageType = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override public ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType getMessageType() {
      ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType result = ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType.forNumber(messageType_);
      return result == null ? ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType.UNRECOGNIZED : result;
    }

    public static final int NEWCONFIG_FIELD_NUMBER = 2;
    private ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto newConfig_;
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
     * @return Whether the newConfig field is set.
     */
    @java.lang.Override
    public boolean hasNewConfig() {
      return newConfig_ != null;
    }
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
     * @return The newConfig.
     */
    @java.lang.Override
    public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto getNewConfig() {
      return newConfig_ == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance() : newConfig_;
    }
    /**
     * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
     */
    @java.lang.Override
    public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder getNewConfigOrBuilder() {
      return newConfig_ == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance() : newConfig_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageType_ != ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType.EmptyMessage.getNumber()) {
        output.writeEnum(1, messageType_);
      }
      if (newConfig_ != null) {
        output.writeMessage(2, getNewConfig());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageType_ != ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType.EmptyMessage.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_);
      }
      if (newConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getNewConfig());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico)) {
        return super.equals(obj);
      }
      ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico other = (ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico) obj;

      if (messageType_ != other.messageType_) return false;
      if (hasNewConfig() != other.hasNewConfig()) return false;
      if (hasNewConfig()) {
        if (!getNewConfig()
            .equals(other.getNewConfig())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      if (hasNewConfig()) {
        hash = (37 * hash) + NEWCONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getNewConfig().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ca.stefanm.e39.proto.PiToPico}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ca.stefanm.e39.proto.PiToPico)
        ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPicoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.stefanm.e39.proto.PiToPicoOuterClass.internal_static_ca_stefanm_e39_proto_PiToPico_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.stefanm.e39.proto.PiToPicoOuterClass.internal_static_ca_stefanm_e39_proto_PiToPico_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.class, ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.Builder.class);
      }

      // Construct using ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        messageType_ = 0;
        newConfig_ = null;
        if (newConfigBuilder_ != null) {
          newConfigBuilder_.dispose();
          newConfigBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.stefanm.e39.proto.PiToPicoOuterClass.internal_static_ca_stefanm_e39_proto_PiToPico_descriptor;
      }

      @java.lang.Override
      public ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico getDefaultInstanceForType() {
        return ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.getDefaultInstance();
      }

      @java.lang.Override
      public ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico build() {
        ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico buildPartial() {
        ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico result = new ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.messageType_ = messageType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.newConfig_ = newConfigBuilder_ == null
              ? newConfig_
              : newConfigBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico) {
          return mergeFrom((ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico other) {
        if (other == ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.getDefaultInstance()) return this;
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (other.hasNewConfig()) {
          mergeNewConfig(other.getNewConfig());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                messageType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getNewConfigFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int messageType_ = 0;
      /**
       * <code>.ca.stefanm.e39.proto.PiToPico.MessageType messageType = 1;</code>
       * @return The enum numeric value on the wire for messageType.
       */
      @java.lang.Override public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <code>.ca.stefanm.e39.proto.PiToPico.MessageType messageType = 1;</code>
       * @param value The enum numeric value on the wire for messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.PiToPico.MessageType messageType = 1;</code>
       * @return The messageType.
       */
      @java.lang.Override
      public ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType getMessageType() {
        ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType result = ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType.forNumber(messageType_);
        return result == null ? ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ca.stefanm.e39.proto.PiToPico.MessageType messageType = 1;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.PiToPico.MessageType messageType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 0;
        onChanged();
        return this;
      }

      private ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto newConfig_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder> newConfigBuilder_;
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
       * @return Whether the newConfig field is set.
       */
      public boolean hasNewConfig() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
       * @return The newConfig.
       */
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto getNewConfig() {
        if (newConfigBuilder_ == null) {
          return newConfig_ == null ? ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance() : newConfig_;
        } else {
          return newConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
       */
      public Builder setNewConfig(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto value) {
        if (newConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          newConfig_ = value;
        } else {
          newConfigBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
       */
      public Builder setNewConfig(
          ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder builderForValue) {
        if (newConfigBuilder_ == null) {
          newConfig_ = builderForValue.build();
        } else {
          newConfigBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
       */
      public Builder mergeNewConfig(ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto value) {
        if (newConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            newConfig_ != null &&
            newConfig_ != ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance()) {
            getNewConfigBuilder().mergeFrom(value);
          } else {
            newConfig_ = value;
          }
        } else {
          newConfigBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
       */
      public Builder clearNewConfig() {
        bitField0_ = (bitField0_ & ~0x00000002);
        newConfig_ = null;
        if (newConfigBuilder_ != null) {
          newConfigBuilder_.dispose();
          newConfigBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
       */
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder getNewConfigBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getNewConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
       */
      public ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder getNewConfigOrBuilder() {
        if (newConfigBuilder_ != null) {
          return newConfigBuilder_.getMessageOrBuilder();
        } else {
          return newConfig_ == null ?
              ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.getDefaultInstance() : newConfig_;
        }
      }
      /**
       * <code>.ca.stefanm.e39.proto.ConfigProto newConfig = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder> 
          getNewConfigFieldBuilder() {
        if (newConfigBuilder_ == null) {
          newConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProto.Builder, ca.stefanm.e39.proto.ConfigProtoOuterClass.ConfigProtoOrBuilder>(
                  getNewConfig(),
                  getParentForChildren(),
                  isClean());
          newConfig_ = null;
        }
        return newConfigBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ca.stefanm.e39.proto.PiToPico)
    }

    // @@protoc_insertion_point(class_scope:ca.stefanm.e39.proto.PiToPico)
    private static final ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico();
    }

    public static ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PiToPico>
        PARSER = new com.google.protobuf.AbstractParser<PiToPico>() {
      @java.lang.Override
      public PiToPico parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PiToPico> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PiToPico> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.stefanm.e39.proto.PiToPicoOuterClass.PiToPico getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_stefanm_e39_proto_PiToPico_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_stefanm_e39_proto_PiToPico_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016PiToPico.proto\022\024ca.stefanm.e39.proto\032\021" +
      "ConfigProto.proto\"\224\004\n\010PiToPico\022?\n\013messag" +
      "eType\030\001 \001(\0162*.ca.stefanm.e39.proto.PiToP" +
      "ico.MessageType\0224\n\tnewConfig\030\002 \001(\0132!.ca." +
      "stefanm.e39.proto.ConfigProto\"\220\003\n\013Messag" +
      "eType\022\020\n\014EmptyMessage\020\000\022\024\n\020HeartbeatRequ" +
      "est\020\001\022\025\n\021HeartbeatResponse\020\002\022\027\n\023ConfigSt" +
      "atusRequest\020\003\022\016\n\nConfigPush\020\004\022\034\n\030PicoVid" +
      "eoRequestUpstream\020\005\022\030\n\024PicoVideoRequestP" +
      "ico\020\006\022\027\n\023PicoVideoRequestRpi\020\007\022\027\n\023PicoVi" +
      "deoRequestRVC\020\010\022\026\n\022PicoPowerRequestOn\020\t\022" +
      "\027\n\023PicoPowerRequestOff\020\n\022\036\n\032SimulatedIgn" +
      "itionPosition0\020\013\022\036\n\032SimulatedIgnitionPos" +
      "ition1\020\014\022\036\n\032SimulatedIgnitionPosition2\020\r" +
      "\022\036\n\032SimulatedIgnitionPosition3\020\016b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.stefanm.e39.proto.ConfigProtoOuterClass.getDescriptor(),
        });
    internal_static_ca_stefanm_e39_proto_PiToPico_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ca_stefanm_e39_proto_PiToPico_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_stefanm_e39_proto_PiToPico_descriptor,
        new java.lang.String[] { "MessageType", "NewConfig", });
    ca.stefanm.e39.proto.ConfigProtoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
